name: Sync Docs

on:
  # 允许手动push触发
  #  push:
  #    branches:
  #      - master
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@master

      - name: 安装node环境
        uses: actions/setup-node@master
        with:
          node-version: "18.x"

      - name: 安装依赖
        run: |
          export TZ='Asia/Shanghai'
          npm install --prod

      - name: 拉取文档
        env:
          YUQUE_USERNAME: ${{ secrets.YUQUE_USERNAME }}
          YUQUE_PASSWORD: ${{ secrets.YUQUE_PASSWORD }}
          YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
          YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
          QINIU_SECRET_ID: ${{ secrets.QINIU_SECRET_ID }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
          QINIU_HOST: ${{ secrets.QINIU_HOST }}
        run: |
          npm run elog:sync-short
      #          npm run elog:sync

      - name: 配置Git用户名邮箱
        run: |
          git config --global user.name "sourbell"
          git config --global user.email "bitcoment@gmail.com"

      - name: 提交拉取的文档到GitHub仓库
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "Refresh elog.cache.json" -a

      - name: 推送文档到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
